CREATE TABLE PRODUCTS(
    IDPRODUCTO INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(30),
    CANTIDAD INT,
    PRECIO DOUBLE);

CREATE TABLE ORDERS(
    ORDERID INT NOT NULL PRIMARY KEY,
    NOMBRECLIENTE VARCHAR(60),
    DIRECCION VARCHAR(100));

CREATE TABLE ORDERDETAILS(
    ORDERID INT NOT NULL , 
    PRODUCTID INT NOT NULL , 
    CANTIDAD INT NOT NULL , 
    INDEX ORDERID (ORDERID), 
    INDEX PRODUCTID (PRODUCTID));
    ALTER TABLE ORDERDETAILS ADD FOREIGN KEY(PRODUCTID) REFERENCES PRODUCTS(PRODUCTID);
    ALTER TABLE ORDERDETAILS ADD FOREIGN KEY(ORDERID) REFERENCES ORDERS(ORDERID);

SELECT  `ORDERS`.`ORDERID` AS NOFACTURA,
        `PRODUCTS`.`NOMBRE` AS PRODUCTO,
		`ORDERDETAILS`.`CANTIDAD` AS CANTIDAD,
        `PRODUCTS`.`PRECIO` AS PRECIO
FROM ORDERDETAILS
INNER JOIN PRODUCTS ON `PRODUCTS`.PRODUCTID = `ORDERDETAILS`.`PRODUCTID`
INNER JOIN ORDERS ON `ORDERS`.`ORDERID` = `ORDERDETAILS`.`ORDERID`;