CREATE DATABASE systemjb;

CREATE TABLE PRODUCTS(
    PRODUCTID INT NOT NULL AUTO_INCREMENT,
    PRODUCTO VARCHAR(30),
    CANTIDAD INT,
    PRECIO DOUBLE,
    PRIMARY KEY(PRODUCTId));

CREATE TABLE ORDERS(
    ORDERID INT NOT NULL AUTO_INCREMENT,
    NOMBRECLIENTE VARCHAR(60),
    DIRECCION VARCHAR(100),
    PRIMARY KEY(ORDERID));

CREATE TABLE ORDERDETAILS(
    ORDERID INT NOT NULL , 
    PRODUCTID INT NOT NULL , 
    CANTIDAD INT NOT NULL , 
    FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID), 
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID));

SELECT  `ORDERS`.`ORDERID` AS NOFACTURA,
        `PRODUCTS`.`NOMBRE` AS PRODUCTO,
		`ORDERDETAILS`.`CANTIDAD` AS CANTIDAD,
        `PRODUCTS`.`PRECIO` AS PRECIO
FROM ORDERDETAILS
INNER JOIN PRODUCTS ON `PRODUCTS`.PRODUCTID = `ORDERDETAILS`.`PRODUCTID`
INNER JOIN ORDERS ON `ORDERS`.`ORDERID` = `ORDERDETAILS`.`ORDERID`;
SELECT  `ORDERS`.`ORDERID` AS NOFACTURA,
        `PRODUCTS`.`NOMBRE` AS PRODUCTO,
		`ORDERDETAILS`.`CANTIDAD` AS CANTIDAD,
        `PRODUCTS`.`PRECIO` AS PRECIO
FROM ORDERDETAILS
INNER JOIN PRODUCTS ON `PRODUCTS`.PRODUCTID = `ORDERDETAILS`.`PRODUCTID`
INNER JOIN ORDERS ON `ORDERS`.`ORDERID` = `ORDERDETAILS`.`ORDERID`;